### ISSUE TITLE
disassembler.cc might need <inttypes.h> header.

### ISSUE THREAD

**Issue by ndevillers** [finixbit/ftrace#1]
I had to add `#include <inttypes.h>` in dissassembler.cc to prevent the following error during compilation:

```
source/disassembler.cc:80:18: error: expected ‘)’ before ‘PRIx64’
     printf("0x%" PRIx64 ":\t%s\t\t%s\n", disassembled_ins.address, 
```

**Comment by finixbit** [comment]
issue has been fixed in https://github.com/finixbit/ftrace/commit/1bc5099864c7eadc5846a14e0027ab07daca6549
